# Dockerfile for Development Environment

# Use Python slim image for development
FROM python:3.12-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=windforlife.settings.dev

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app
COPY requirements.dev.txt /app
RUN pip install --upgrade pip && \
    pip install -r requirements.dev.txt

# Copy application source code
COPY . /app

# Expose port for development
EXPOSE 8000

# Run Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000", "--settings=windforlife.settings.dev"]
