# Generated by Django 4.2 on 2025-05-06 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anemometer',
            name='latitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='anemometer',
            name='longitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='anemometer',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='windspeedreading',
            name='recorded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='anemometer',
            index=models.Index(fields=['latitude', 'longitude'], name='api_anemome_latitud_8bc195_idx'),
        ),
    ]
